export const authConstants = {
    GET_USER_OR_RESTAURANT_DATA: "GET_USER_OR_RESTAURANT_DATA",
}

export const restaurantConstants = {
    GET_RESTAURANTS_AFTER_SEARCH_REQUEST: "GET_RESTAURANTS_AFTER_SEARCH_REQUEST",
    GET_RESTAURANTS_AFTER_SEARCH_SUCCESS: "GET_RESTAURANTS_AFTER_SEARCH_SUCCESS",
    GET_RESTAURANTS_AFTER_SEARCH_FAILURE: "GET_RESTAURANTS_AFTER_SEARCH_FAILURE",
    GET_SINGLE_RESTAURANT_BY_ID_REQUEST: "GET_SINGLE_RESTAURANT_BY_ID_REQUEST",
    GET_SINGLE_RESTAURANT_BY_ID_SUCCESS: "GET_SINGLE_RESTAURANT_BY_ID_SUCCESS",
    GET_SINGLE_RESTAURANT_BY_ID_FAILURE: "GET_SINGLE_RESTAURANT_BY_ID_FAILURE",
}