export const authConstants = {
    GET_USER_OR_RESTAURANT_DATA: "GET_USER_OR_RESTAURANT_DATA",
}

export const restaurantConstants = {
    GET_RESTAURANTS_AFTER_SEARCH_REQUEST: "GET_RESTAURANTS_AFTER_SEARCH_REQUEST",
    GET_RESTAURANTS_AFTER_SEARCH_SUCCESS: "GET_RESTAURANTS_AFTER_SEARCH_SUCCESS",
    GET_RESTAURANTS_AFTER_SEARCH_FAILURE: "GET_RESTAURANTS_AFTER_SEARCH_FAILURE",
    GET_SINGLE_RESTAURANT_BY_ID_REQUEST: "GET_SINGLE_RESTAURANT_BY_ID_REQUEST",
    GET_SINGLE_RESTAURANT_BY_ID_SUCCESS: "GET_SINGLE_RESTAURANT_BY_ID_SUCCESS",
    GET_SINGLE_RESTAURANT_BY_ID_FAILURE: "GET_SINGLE_RESTAURANT_BY_ID_FAILURE",
}

export const reviewConstants = {
    OPEN_REVIEW_FORM_MODAL: "OPEN_REVIEW_FORM_MODAL",
    CLOSE_REVIEW_FORM_MODAL: "CLOSE_REVIEW_FORM_MODAL",
    GET_REVIEWS_BY_RESTAURANT_ID_REQUEST: "GET_REVIEWS_BY_RESTAURANT_ID_REQUEST",
    GET_REVIEWS_BY_RESTAURANT_ID_SUCCESS: "GET_REVIEWS_BY_RESTAURANT_ID_SUCCESS",
    GET_REVIEWS_BY_RESTAURANT_ID_FAILURE: "GET_REVIEWS_BY_RESTAURANT_ID_FAILURE",
    GET_SINGLE_REVIEW_BY_ID_REQUEST: "GET_SINGLE_REVIEW_BY_ID_REQUEST",
    GET_SINGLE_REVIEW_BY_ID_SUCCESS: "GET_SINGLE_REVIEW_BY_ID_SUCCESS",
    GET_SINGLE_REVIEW_BY_ID_FAILURE: "GET_SINGLE_REVIEW_BY_ID_FAILURE",
}

export const commentConstants = {
    GET_COMMENTS_BY_REVIEW_ID_REQUEST: "GET_COMMENTS_BY_REVIEW_ID_REQUEST",
    GET_COMMENTS_BY_REVIEW_ID_SUCCESS: "GET_COMMENTS_BY_REVIEW_ID_SUCCESS",
    GET_COMMENTS_BY_REVIEW_ID_FAILURE: "GET_COMMENTS_BY_REVIEW_ID_FAILURE",
}